# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fecf8d5cd446138ad7bfeb3a9b2151eae0986690d95b85cf66fe0088148ac9fbc5ffcd3d2f5f1b33a8f67e4e3400315e8d5e66f262399191f239216c6fb9a22f

test:
  secret_key_base: b216c40493a74548811be7a1398b58a1080e7561328fdfab3e9fa184039e60f5755e531a9fcea955b4ecb5cc064c75b2cb1170a43c8cbdb4016b8d3f31acd335

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
